/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services.web-development'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesMobileDevelopmentRouteImport } from './routes/services.mobile-development'
import { Route as ServicesErpSoftwareRouteImport } from './routes/services.erp-software'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services.digital-marketing'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AdminRenewalsRouteImport } from './routes/admin.renewals'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileDevelopmentRoute =
  ServicesMobileDevelopmentRouteImport.update({
    id: '/mobile-development',
    path: '/mobile-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesErpSoftwareRoute = ServicesErpSoftwareRouteImport.update({
  id: '/erp-software',
  path: '/erp-software',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/digital-marketing',
    path: '/digital-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRenewalsRoute = AdminRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-software': typeof ServicesErpSoftwareRoute
  '/services/mobile-development': typeof ServicesMobileDevelopmentRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/admin/': typeof AdminIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-software': typeof ServicesErpSoftwareRoute
  '/services/mobile-development': typeof ServicesMobileDevelopmentRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/admin': typeof AdminIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/erp-software': typeof ServicesErpSoftwareRoute
  '/services/mobile-development': typeof ServicesMobileDevelopmentRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/admin/': typeof AdminIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/services'
    | '/admin/content'
    | '/admin/deals'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/renewals'
    | '/portfolio/$slug'
    | '/services/digital-marketing'
    | '/services/erp-software'
    | '/services/mobile-development'
    | '/services/seo'
    | '/services/web-development'
    | '/admin/'
    | '/portfolio/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/content'
    | '/admin/deals'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/renewals'
    | '/portfolio/$slug'
    | '/services/digital-marketing'
    | '/services/erp-software'
    | '/services/mobile-development'
    | '/services/seo'
    | '/services/web-development'
    | '/admin'
    | '/portfolio'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/services'
    | '/admin/content'
    | '/admin/deals'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/renewals'
    | '/portfolio/$slug'
    | '/services/digital-marketing'
    | '/services/erp-software'
    | '/services/mobile-development'
    | '/services/seo'
    | '/services/web-development'
    | '/admin/'
    | '/portfolio/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-development': {
      id: '/services/mobile-development'
      path: '/mobile-development'
      fullPath: '/services/mobile-development'
      preLoaderRoute: typeof ServicesMobileDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/erp-software': {
      id: '/services/erp-software'
      path: '/erp-software'
      fullPath: '/services/erp-software'
      preLoaderRoute: typeof ServicesErpSoftwareRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/renewals': {
      id: '/admin/renewals'
      path: '/renewals'
      fullPath: '/admin/renewals'
      preLoaderRoute: typeof AdminRenewalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminRenewalsRoute: typeof AdminRenewalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminRenewalsRoute: AdminRenewalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesErpSoftwareRoute: typeof ServicesErpSoftwareRoute
  ServicesMobileDevelopmentRoute: typeof ServicesMobileDevelopmentRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesErpSoftwareRoute: ServicesErpSoftwareRoute,
  ServicesMobileDevelopmentRoute: ServicesMobileDevelopmentRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
